METHOD IF_HTTP_EXTENSION~HANDLE_REQUEST.

  " ==========================================
  " DEKLARASI HTTP & INPUT POSTMAN
  " ==========================================

  DATA: LV_TYPE      TYPE STRING,
        LV_JSON_DATA TYPE STRING.

  " ==========================================
  " DEKLARASI STRUKTUR
  " ==========================================
  DATA: LV_RAW_DATA TYPE STRING,
        LV_MSG      TYPE STRING,
        LV_PR_TYPE    TYPE STRING,
        LV_ITEM_STR   TYPE STRING,
        LT_ITEMS    TYPE TABLE OF STRING,
        LV_ITEM     TYPE STRING,
        LT_FIELDS   TYPE TABLE OF STRING,
        LV_MAT      TYPE STRING,
        LV_QTY      TYPE STRING,
        LV_PLANT    TYPE STRING.


" ==========================================
  " DEKLARASI BAPI
  " ==========================================
  DATA: LT_REQ_ITEMS TYPE TABLE OF BAPIEBANC,
        LS_REQ_ITEM  TYPE BAPIEBANC,
        LT_RETURN    TYPE TABLE OF BAPIRETURN, " Perhatikan tipenya BAPIRETURN
        LS_RETURN    TYPE BAPIRETURN,
        LV_PR_NUMBER TYPE BAPIEBANC-PREQ_NO.

  DATA: LV_ITEM_NO    TYPE N LENGTH 5,
        LV_ERROR_FLAG TYPE C LENGTH 1.

  LV_TYPE = SERVER->REQUEST->GET_HEADER_FIELD( NAME = '~request_method' ).

  FIELD-SYMBOLS: <FS_PARAM> TYPE IHTTPNVP.

  IF LV_TYPE NE 'POST'.
    CALL METHOD SERVER->RESPONSE->SET_HEADER_FIELD( NAME = 'Allow' VALUE = 'POST' ).
    CALL METHOD SERVER->RESPONSE->SET_STATUS( CODE = '405' REASON = 'Method not allowed' ).
    EXIT.
  ENDIF.

  LV_RAW_DATA = SERVER->REQUEST->GET_CDATA( ).

  " Split Items'#' - HEADER.
  SPLIT LV_RAW_DATA AT '#' INTO LV_PR_TYPE LV_ITEM_STR.
  IF LV_PR_TYPE IS INITIAL. LV_PR_TYPE = 'NB'. ENDIF.

  " Split Items ';'.
  SPLIT LV_ITEM_STR AT ';' INTO TABLE LT_ITEMS.


  LOOP AT LT_ITEMS INTO LV_ITEM.
    SPLIT LV_ITEM AT '|' INTO LV_MAT LV_QTY LV_PLANT.

    IF LV_MAT IS NOT INITIAL.
      CLEAR LS_REQ_ITEM.

      TRANSLATE LV_MAT TO UPPER CASE.
      LS_REQ_ITEM-MATERIAL = LV_MAT.

      " Item PR
      LS_REQ_ITEM-PREQ_ITEM  = LV_ITEM_NO.
      LS_REQ_ITEM-DOC_TYPE   = LV_PR_TYPE.
      LS_REQ_ITEM-QUANTITY   = LV_QTY.
      LS_REQ_ITEM-PLANT      = LV_PLANT.
      LS_REQ_ITEM-UNIT       = 'PC'.
      LS_REQ_ITEM-DELIV_DATE = SY-DATUM + 7.

      APPEND LS_REQ_ITEM TO LT_REQ_ITEMS.

      LV_ITEM_NO = LV_ITEM_NO + 10.
    ENDIF.
  ENDLOOP.

  " EKSEKUSI BAPI
CALL FUNCTION 'BAPI_REQUISITION_CREATE'
    IMPORTING
      NUMBER            = LV_PR_NUMBER
    TABLES
      REQUISITION_ITEMS = LT_REQ_ITEMS
      RETURN            = LT_RETURN.

  " COMMIT & RESPONSE
  CLEAR: LV_ERROR_FLAG, LV_MSG.

  LOOP AT LT_RETURN INTO LS_RETURN WHERE TYPE = 'E' OR TYPE = 'A'.
    LV_ERROR_FLAG = 'X'.
    IF LV_MSG IS INITIAL.
      CONCATENATE 'Error:' LS_RETURN-MESSAGE INTO LV_MSG SEPARATED BY SPACE.
    ELSE.
      CONCATENATE LV_MSG '|' LS_RETURN-MESSAGE INTO LV_MSG SEPARATED BY SPACE.
    ENDIF.
  ENDLOOP.

  IF LV_ERROR_FLAG IS INITIAL.
    CALL FUNCTION 'BAPI_TRANSACTION_COMMIT' EXPORTING WAIT = 'X'.
    CONCATENATE 'Sukses! PR: ' LV_PR_NUMBER INTO LV_MSG.
  ELSE.
    CALL FUNCTION 'BAPI_TRANSACTION_ROLLBACK'.
  ENDIF.

  CALL METHOD SERVER->RESPONSE->SET_HEADER_FIELD
    EXPORTING NAME = 'Content-Type' VALUE = 'text/plain'.

  CALL METHOD SERVER->RESPONSE->SET_CDATA
    EXPORTING DATA = LV_MSG.

ENDMETHOD.